<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >


    <!-- LIDAR -->

    <joint name="laser_joint" type="fixed">
        <parent link="base_link"/>
        <child link="laser_frame"/>
        <origin xyz="0.10 0 ${-wheel_offset_z + 0.66}" rpy="0 0 0"/>
    </joint>

    <link name="laser_frame">
        <visual>
            <geometry>
                <cylinder radius="0.05" length="0.04"/>
            </geometry>
            <material name="black"/>
        </visual>
        <visual>
            <origin xyz="0 0 0"/>
            <geometry>
                <cylinder radius="0.07" length="0.1"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.05" length="0.04"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.1" length="0.04" radius="0.05">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo>
        <plugin
        filename="libignition-gazebo-sensors-system.so"
        name="ignition::gazebo::systems::Sensors">
        <render_engine>ogre2</render_engine>
        </plugin>
    </gazebo>

    <gazebo reference="laser_frame">
        <material>Gazebo/Black</material>
        <sensor name="laser_frame" type="gpu_lidar">
            <ignition_frame_id>laser_frame</ignition_frame_id>
            <pose relative_to='laser_frame'> 0 0 0 0 0 4.713 </pose>
            <topic>scan</topic>
            <visualize>true</visualize>
            <update_rate>5</update_rate>
            <ray>
                <scan>
                    <horizontal>
                        <samples>360</samples>
                        <min_angle>0</min_angle>
                        <min_angle>-3.14</min_angle>
                        <max_angle>3.14</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.08</min>
                    <max>20.0</max>
                </range>
            </ray>
            <always_on>1</always_on>
        </sensor>
    </gazebo>



    <!-- LIDAR HOLDER -->

    <joint name="mount_joint" type="fixed"> 
        <parent link="chassis"/>
        <child link="lidar_holder"/>
        <origin xyz="0 0 0.466" rpy="0 0 0"/>
    </joint>

    <link name="lidar_holder">
         <visual>
            <geometry>
                <box size="0.40 0.14 0.03"/>
            </geometry>
            <material name="grey"/>
        </visual>
        <collision>
            <geometry>
                <box size="0.25 0.14 0.03"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.01" x="0.25" y="0.14" z="0.03">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>

    </link>

    <gazebo reference="lidar_holder">
        <material>Gazebo/Grey</material>
    </gazebo>

</robot>