<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <joint name="battery_joint" type="fixed">
        <parent link="chassis"/>
        <child link="battery_pack"/>
        <origin xyz="${-chassis_length + (chassis_length/4) } 0 ${chassis_height/2}" rpy="0 0 0"/>
    </joint>

    <link name="battery_pack">
        <visual>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="${chassis_length/2} ${chassis_width/2} ${chassis_height/2}"/>
            </geometry>
            <material name="lightgrey"/>
        </visual>
        <collision>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="${chassis_length/2} ${chassis_width/2} ${chassis_height/2}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="2.0" x="0.3" y="0.5" z="0.3">
            <origin xyz="${chassis_length/2} ${chassis_width/2} -0.5" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="battery_pack">
        <material>Gazebo/LightGrey</material>
    </gazebo>

</robot>