<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  
  <!-- Define parameters -->
  <xacro:property name="plow_height" value="${chassis_height - 0.2}"/> <!-- Height of the snowplow blade -->
  <xacro:property name="plow_width" value="1.5"/> <!-- Width of the snowplow blade -->
  <xacro:property name="plow_length" value="0.1"/> <!-- Length of the snowplow blade -->
  <xacro:property name="sphere_radius" value="0.05"/> <!-- Radius of the sphere -->
  <xacro:property name="sphere_height" value="${chassis_height/2 - 0.1}"/> <!-- Height of the sphere -->
  <xacro:property name="bar_length" value="${0.32-sphere_radius}"/> <!-- Height of the sphere -->

  <!-- Define materials -->
  <!-- <material name="grey">
    <color rgba="0.5 0.5 0.5 1"/>
  </material> -->


<!-- plow holder -->

  <joint name="blade_bar_joint" type="fixed">
        <parent link="chassis"/>
        <child link="blade_bar"/>
        <origin xyz="${bar_length/2} 0 ${chassis_height/2 - 0.2}" rpy="0 ${pi/2} 0" />
    </joint>

    <link name="blade_bar">
        <visual>
            <geometry>
                <cylinder radius="0.01" length="${bar_length}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.01" length="${bar_length}"/>
            </geometry>
        </collision>
    </link>
    

    <gazebo reference="blade_bar">
        <material>Gazebo/white</material>
    </gazebo>


    <!-- plow  -->
    <joint name="blade_joint" type="fixed">
        <parent link ="blade_bar" />
        <child link ="snowplow_blade_link" />
        <origin xyz="0 0 ${bar_length/2 + sphere_radius}" rpy="0 ${-pi/2} 0" />
    </joint>

  
  <!-- Define the link -->
  <link name="snowplow_blade_link">
    <!-- Visual representation of the snowplow blade -->
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <!-- Sphere for the back part -->
      <geometry>
        <sphere radius="${sphere_radius}" scale="1 9 1"/>
      </geometry>
      <!-- Apply grey material -->
      <material name="grey"/>
    </visual>
    <!-- Collision representation (same as visual for simplicity) -->
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <!-- Sphere for the back part -->
      <geometry>
        <sphere radius="${sphere_radius}" scale="1 2 1"/>
      </geometry>
    </collision>
    <!-- Front part of the snowplow blade (box) -->
    <visual>
      <origin xyz="${plow_length / 2} 0 -0.01" rpy="0 0 0"/>
      <geometry>
        <box size="${plow_length} ${plow_width} ${plow_height}"/>
      </geometry>
      <!-- Apply grey material -->
      <material name="grey"/>
    </visual>
    <!-- Collision representation (same as visual for simplicity) -->
    <collision>
      <origin xyz="${plow_length / 2} 0 -0.01" rpy="0 0 0"/>
      <geometry>
        <box size="${plow_length} ${plow_width} ${plow_height}"/>
      </geometry>
    </collision>
  </link>

  <!-- Gazebo specific properties -->
  <gazebo reference="snowplow_blade_link">
    <!-- <mu1>1000</mu1> Friction coefficient -->
    <!-- <mu2>1000</mu2> Friction coefficient -->
    <material>Gazebo/Grey</material> <!-- Gazebo built-in material -->
  </gazebo>

</robot>
